<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.135
     Generated on:       05.02.2017 14:43
     Generated by:       Friedrich Weinmann
     Organization:       Infernal Associates ltd.
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2017
#>


. "$PSScriptRoot\Libraries\library.ps1"

$scripts =  Get-ChildItem "$PSScriptRoot\Functions" -Recurse -Include *.ps1
foreach ($script in $scripts) { . $script }